/* 
	Data processing using SAS 
	Assessment 2
	Autumn 2022
	
	Name: Syed Jazil Hussain
	Student number: 14369793
	
*/

libname practice "/home/u60956011/Jazil_personal/DP using SAS/datasets/Datasets - Practice";


proc import datafile= '/home/u60956011/Jazil_personal/DP using SAS/datasets/Datasets - Practice/metadata-easier.csv'
	dbms=csv
	out=practice.metadata
	replace;
guessingrows=300;


proc import datafile= '/home/u60956011/Jazil_personal/DP using SAS/datasets/Datasets - Practice/keywords.csv'
	dbms=csv
	out=practice.keywords
	replace;

proc contents data=practice.metadata;
Title 'Contents of the Metadata data set';
run;

proc contents data=practice.keywords;
Title 'Contents of the Keywords data set';
run;

ods pdf file='/home/u60956011/Jazil_personal/Export/metadata_keywords.pdf' style=analysis;

/*
Merging the two data sets
*/

proc sort data=practice.metadata out=practice.metadata_sorted;
	by id;
run;

data metadata_keywords;
	merge practice.metadata_sorted practice.keywords;
	by id;
run;

/*
Removing Duplicates
*/

proc sort data=metadata_keywords nodupkey;
	by id;
run;



/*
What's the average review score for movies? Has this changed over time?
*/


data review;
	set metadata_keywords;
	keep original_title release_date vote_average;
	where release_date is not missing;
run;

Title Release Date Of Movies In Ascending Order;
proc sort data=review;
	by release_date;
run;

ods noproctitle; 
Title "Average Review Score For Movies";
proc means data=review;
	var vote_average;
	label vote_average = Vote Average;
run;




ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=WORK.REVIEW;
	title height=14pt "Average Movie Ratings Throughout The Years";
	footnote2 justify=left height=12pt 
		"Movies before the 1930's had higher ratings. The movie ratings have varied more in the later years.";
	scatter x=release_date y=vote_average /;
	xaxis grid;
	yaxis grid;
run;

ods graphics / reset;
title;



/*
What are the detailed summary statistics of the variable 'revenue' and the maximum revenue a movie has generated?
*/


ods noproctitle;
title1 "Revenue analysis";
proc univariate data=metadata_keywords;
 var revenue;
 
 output  out = maximum_revenue
 	max = max_value;
 	
run; 

proc print data = maximum_revenue noobs;
title "Highest revenue generated by a movie";
run;


/*
What genres are popular?
*/


data genre;
set metadata_keywords;
keep genres popularity release_date; 
format release_date MMDDYY10.;
run;


proc freq data=metadata_keywords order=freq;
	tables genres/ out=freqgenre nopercent noprint;
	where genres is not missing;
run; 
proc print data=freqgenre (obs=10);
title "Top 10 most popular genre's throughout the years";
run;



proc template;
	define statgraph SASStudio.Pie;
	title height=14pt "Percentage distribution of the popularity of each genre";
	footnote2 justify=center height=12pt 
		"Drama is the most popular genre at 11.62%";
		begingraph;
		layout region;
		piechart category=genres / stat=pct datalabellocation=inside;
		endlayout;
		endgraph;
	end;
run;

ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgrender template=SASStudio.Pie data=WORK.GENRE;
run;

ods graphics / reset;


/*
Calculate the revenue of each main genre
*/

%let genres = Drama;
title Average Drama;
proc means data=metadata_keywords;
	where genres = "&genres";
	var revenue;
run;

%let genres = Documentary;
title Average Documentary;
proc means data=metadata_keywords;
	where genres = "&genres";
	var revenue;
run;

%let genres = Comedy;
title Average Comedy;
proc means data=metadata_keywords;
	where genres = "&genres";
	var revenue;
run;

%let genres = Horror;
title Average Horror;
proc means data=metadata_keywords;
	where genres = "&genres";
	var revenue;
run;





/*
What is the most popular comedy movie and how does the popularity of the comedy genre change over time?
*/


data comedy_genre;
	set metadata_keywords;
	keep genres popularity release_date;
	where genres contains 'Comedy';
run; 




ods graphics / reset width=6.4in height=4.8in imagemap;

proc sort data=WORK.COMEDY_GENRE out=_SeriesPlotTaskData;
	by release_date;
run;

proc sgplot data=_SeriesPlotTaskData;
	title height=14pt "Popularity of Comedy Movies Over Time";
	footnote2 justify=left height=12pt 
		"Only Genres Which Contain 'Comedy' Have Been Included";
	series x=release_date y=popularity / group=genres;
	xaxis grid;
	yaxis grid;
run;

ods graphics / reset;
title;
footnote2;

proc datasets library=WORK noprint;
	delete _SeriesPlotTaskData;
	run;



/*
Does production budget relate to popularity?
*/

title "Correlation between budget and popularity";
proc corr data=metadata_keywords;
	var budget popularity;
run; 


data budgetcorr;
	set metadata_keywords;
	keep budget popularity;
	where budget is not missing;
	where popularity is not missing; 
run; 



ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=WORK.BUDGETCORR;
	title height=14pt "Correlation Between Budget and Popularity";
	reg x=budget y=popularity / nomarkers;
	scatter x=budget y=popularity /;
	xaxis grid;
	yaxis grid;
run;

ods graphics / reset;
title;


/*
Which movies are rated 'Good', 'Moderate' & 'Bad'?
*/


data movierating;
	set metadata_keywords;
	length rating $15;

	where vote_average is not missing and title is not missing;
	
	if vote_average > 7 then rating = 'Good';
	else if voteaverage < 4  then rating = 'Bad';
	else rating = 'Moderate';
run;

title "Which movies are considered 'Good', 'Moderate' or 'Bad' based on ratings";	
proc print data=movierating (obs=20);
var title rating;
run;



/*
Which movies had a high or low budget?
*/

proc format;
	value budget_size low -<500000 = "Low Budget"
				500000 - high = "High Budget"
				;
run; 

data movie_budget;
	set metadata_keywords;
	format budget budget_size.;
	keep title budget;
run;

Title "Which movies have a low budget and which have a high budget?";
proc print data=movie_budget(obs=20);
	var title budget;
run;


/*
Which movies are longer than 2 hours?
*/

data runtime;
	set metadata_keywords;
	duration = input(runtime, ??8.);
	keep title duration;
	where title is not missing;
run; 

Title "Movies longer than 3 hours";
proc print data=runtime(obs=20);
	var title duration;
	where duration > 180;
run;


/*
Exporting
*/

ods pdf close;







